---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/products
  label: Produits
  create: documents
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - produit
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - page
- type: directory
  path: src/posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - post
- type: directory
  path: pages
  label: 'Test pages '
  create: documents
  match: "**/*.md"
  new_doc_ext: ".md"
  templates:
  - test
- type: document
  path: home-test
  label: 'Test Home Page '
  match: "**/*"
- type: heading
  label: Globals
- type: document
  path: src/_data/tokens.json
  label: Theme settings
upload_dir: src/images
public_path: "/11ty-test/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=development
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm start
